### ISSUE TITLE
RFC: yoinking errors

### ISSUE THREAD

**Issue by brainkim** [mikelsr/YeetScript#1]
As a developer, sometimes I may feel the need not to `catch` yeeted errors but `yoink` them instead:

```js
try {
  yeet new Error("YOLO");
} yoink (err) {
  console.log(err);
}

```
Please implement this or I will leave a comment on this issue which says “any progress” like every single day.

**Comment by mikelsr** [comment]
Hi! Just came back from vacation thank you for waiting :)

I'm guessing you could implement it by adding `        yoink: SyntaxKind.CatchKeyword,` to the [keyword list](https://github.com/microsoft/TypeScript/blob/master/src/compiler/scanner.ts#L77). I do this for `yeet` with a [`sed` command on build.sh](https://github.com/mikelsr/YeetScript/blob/master/build.sh#L18).
